jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd"
      - uses: "extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff"
      - uses: "actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5"
        with:
          cache: true
          go-version-file: "terraform-provider/cmd/pull-provider/go.mod"
      - uses: "jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2"
        with:
          repo: "marcbran/jsonnet-kit"
      - name: "Run tests"
        run: |
          cd terraform-provider
          just gen-provider ./providers/registry.terraform.io/hashicorp/dns
    timeout-minutes: 5
name: "Test registry.terraform.io/hashicorp/dns"
"on":
  pull_request:
    paths:
      - "terraform-provider/providers/registry.terraform.io/hashicorp/dns/**"
  workflow_dispatch: {}
permissions:
  contents: "read"